apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "localdns.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "localdns.name" . }}
    chart: {{ include "localdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "localdns.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "localdns.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "localdns.fullname" . }}
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
            - name: NAMESERVER
              value: {{ .Values.nameserver | quote }}
            - name: DOMAIN_NAME
              value: {{ .Values.domainName | quote }}
            - name: RNAME
              value: {{ .Values.rname | quote }}
            - name: PUBLIC_IP
              value: {{ .Values.publicIP | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
          {{- if .Values.envSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecretName }}
          {{- end }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: dns
              containerPort: 53
              protocol: UDP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "localdns.servingCertificate" . }}
        {{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
